// ======================================================================
// calendar-script.js — Roots Calendar Module
// ======================================================================

// ======================================================================
// SECTION: STATE
// ======================================================================

let currentYear   = new Date().getFullYear();
let currentMonth  = new Date().getMonth();
let historyStack  = [];
let redoStack     = [];
let weatherCache  = null;
let accountName   = 'Farmer';
let calendarMode  = 'personal'; // 'personal' | 'community'
let currentView   = 'month';    // 'month' | 'today' | 'week'
let activeLayers  = { tasks: true, da: true, weather: false, moon: false, market: true };
let weekOffset    = 0;

// ======================================================================
// SECTION: PERSONAL EVENTS DATA
// ======================================================================

let calendarEvents = [
  { id:1, dateKey:getDateKey(new Date()), type:'task', emoji:'🌱', title:'Rice Planting – Wet Season', notes:'Upper paddy field, Purok 3. Use certified seeds from DA.', location:'Upper field, Purok 3', crop:'rice', autoGenerated:false },
  { id:2, dateKey:getDateKey(addDays(new Date(),14)), type:'task', emoji:'🌿', title:'Weeding – Rice Field', notes:'First weeding 2 weeks after transplant.', crop:'rice', autoGenerated:true },
  { id:3, dateKey:getDateKey(addDays(new Date(),21)), type:'task', emoji:'🧪', title:'Fertilizer Application (Urea)', notes:'Apply 1 bag urea per hectare. Top-dress after 3 weeks.', crop:'rice', autoGenerated:true },
  { id:4, dateKey:getDateKey(addDays(new Date(),45)), type:'pest', emoji:'🐛', title:'Pest High-Risk Week – Brown Planthopper', notes:'Monitor fields closely. Peak risk during this window.', crop:'rice', autoGenerated:true },
  { id:5, dateKey:getDateKey(addDays(new Date(),90)), type:'harvest', emoji:'🌾', title:'Estimated Harvest – Wet Season Rice', notes:'Expected yield: 4–5 tons/ha. Prepare drying area.', crop:'rice', autoGenerated:true },
  { id:6, dateKey:getDateKey(addDays(new Date(),5)),  type:'da', emoji:'🌱', title:'DA Free Seed Distribution', notes:'Oroquieta City Agricultural Office. Bring barangay ID.', location:'DA Office, Poblacion' },
  { id:7, dateKey:getDateKey(addDays(new Date(),12)), type:'da', emoji:'💉', title:'Livestock Vaccination Drive', notes:'Free Hog Cholera & Rabies vaccines. Brgy. Pines & surrounding areas.', location:'Brgy. Pines Covered Court' },
  { id:8, dateKey:getDateKey(addDays(new Date(),18)), type:'da', emoji:'🎓', title:'Farm Technology Seminar', notes:'Good Agricultural Practices (GAP) training. Register at DA office.', location:'DA Training Hall' },
  { id:9, dateKey:getDateKey(addDays(new Date(),28)), type:'da', emoji:'💰', title:'Fertilizer Subsidy Release', notes:'Registered farmers may claim subsidized fertilizer allocation.', location:'DA Warehouse, Layawan' }
];

// ======================================================================
// SECTION: COMMUNITY EVENTS DATA
// ======================================================================

let communityEvents = [
  { id:'c1', dateKey:getDateKey(addDays(new Date(),2)),  type:'harvest', emoji:'🌾', title:'Palay Harvest – Available for Pickup',  notes:'Freshly harvested palay. 50 cavans available.', location:'Brgy. Dolipos Alto', farmer:'Mang Rudy S.', isPublic:true },
  { id:'c2', dateKey:getDateKey(addDays(new Date(),5)),  type:'harvest', emoji:'🍌', title:'Banana Harvest – Lakatan Ready',          notes:'Lakatan bananas ready for wholesale. 200 kg available.', location:'Brgy. Pines', farmer:'Aling Nena C.', isPublic:true },
  { id:'c3', dateKey:getDateKey(addDays(new Date(),8)),  type:'da',      emoji:'🌱', title:'DA Corn Seed Distribution',               notes:'Open to all registered farmers. First come, first served.', location:'DA Office, Poblacion', farmer:'DA Oroquieta', isPublic:true },
  { id:'c4', dateKey:getDateKey(addDays(new Date(),11)), type:'task',    emoji:'🥬', title:'Fresh Vegetables – Farm Gate Sale',       notes:'Ampalaya, sitaw, and pechay. Farm gate price.', location:'Brgy. Lamac', farmer:'Kuya Ben D.', isPublic:true },
  { id:'c5', dateKey:getDateKey(addDays(new Date(),15)), type:'harvest', emoji:'🥥', title:'Coconut Harvest – Copra Ready',           notes:'Copra and buko available. Bulk buyers preferred.', location:'Brgy. Plaridel', farmer:'Mang Cardo R.', isPublic:true }
];

// ======================================================================
// SECTION: WEATHER PLACEHOLDER + LIVE FETCH
// ======================================================================

const WEATHER_PLACEHOLDER = {
  live: false,
  location: 'Oroquieta City, Misamis Occidental',
  current: { temp:31, humidity:78, condition:'Partly Cloudy', icon:'⛅', wind:'12 km/h NE' },
  alert: null,
  forecast: [
    { day:'Today', icon:'⛅', high:31, low:24, rain:'10%' },
    { day:'Mon',   icon:'🌧️', high:28, low:23, rain:'70%' },
    { day:'Tue',   icon:'⛈️', high:27, low:22, rain:'85%' },
    { day:'Wed',   icon:'🌦️', high:29, low:23, rain:'40%' },
    { day:'Thu',   icon:'☀️', high:33, low:25, rain:'5%'  }
  ]
};

async function fetchWeatherFromPAGASA() {
  try {
    const url = 'https://api.open-meteo.com/v1/forecast?latitude=8.4853&longitude=123.7886' +
      '&current=temperature_2m,relative_humidity_2m,wind_speed_10m,weather_code' +
      '&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max' +
      '&timezone=Asia%2FManila&forecast_days=7';
    const res  = await fetch(url);
    const data = await res.json();
    const wmoIcon = c => c===0?'☀️':c<=3?'⛅':c<=48?'🌫️':c<=67?'🌧️':c<=77?'❄️':c<=82?'🌦️':'⛈️';
    const wmoDesc = c => c===0?'Clear Sky':c<=3?'Partly Cloudy':c<=48?'Foggy':c<=67?'Rainy':c<=82?'Showers':'Thunderstorm';
    const days = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
    const forecast = data.daily.time.slice(0,7).map((d,i) => ({
      day:     i===0 ? 'Today' : days[new Date(d+'T00:00:00').getDay()],
      dateKey: d,
      icon:    wmoIcon(data.daily.weather_code[i]),
      high:    Math.round(data.daily.temperature_2m_max[i]),
      low:     Math.round(data.daily.temperature_2m_min[i]),
      rain:    `${data.daily.precipitation_probability_max[i]}%`
    }));
    return {
      live: true,
      location: 'Oroquieta City, Misamis Occidental',
      current: {
        temp:      Math.round(data.current.temperature_2m),
        humidity:  data.current.relative_humidity_2m,
        condition: wmoDesc(data.current.weather_code),
        icon:      wmoIcon(data.current.weather_code),
        wind:      `${Math.round(data.current.wind_speed_10m)} km/h`
      },
      forecast, alert: null
    };
  } catch {
    const today = new Date();
    WEATHER_PLACEHOLDER.forecast = WEATHER_PLACEHOLDER.forecast.map((f,i) => ({
      ...f, dateKey: getDateKey(addDays(today,i))
    }));
    return WEATHER_PLACEHOLDER;
  }
}

// ======================================================================
// SECTION: DATE & MOON UTILITIES
// ======================================================================

function getDateKey(date) {
  return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
}
function addDays(date, n) { const d = new Date(date); d.setDate(d.getDate()+n); return d; }
function formatDateLabel(dateKey) {
  const d    = new Date(dateKey+'T00:00:00');
  const days = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
  const mons = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  return `${days[d.getDay()]}, ${mons[d.getMonth()]} ${d.getDate()}`;
}
function getDaysUntil(dateKey) {
  const today  = new Date(); today.setHours(0,0,0,0);
  const target = new Date(dateKey+'T00:00:00');
  return Math.round((target - today) / 86400000);
}

const MOON_PHASES = ['🌑','🌒','🌓','🌔','🌕','🌖','🌗','🌘'];
const MOON_NAMES  = ['New Moon','Waxing Crescent','First Quarter','Waxing Gibbous','Full Moon','Waning Gibbous','Last Quarter','Waning Crescent'];
function getMoonPhase(date) {
  const days = Math.floor((date - new Date(2000,0,6)) / 86400000) % 29.53;
  return MOON_PHASES[Math.abs(Math.floor((days/29.53)*8) % 8)];
}
function getMoonPhaseName(date) {
  const days = Math.floor((date - new Date(2000,0,6)) / 86400000) % 29.53;
  return MOON_NAMES[Math.abs(Math.floor((days/29.53)*8) % 8)];
}

// ======================================================================
// SECTION: CROP SCHEDULES + LIFECYCLE GENERATOR
// ======================================================================

const cropSchedules = {
  rice: [
    { offset:0,  type:'task',    emoji:'🌱', title:'Transplanting Day – Rice',             notes:'Use certified seeds. Transplant 20–25-day-old seedlings.' },
    { offset:7,  type:'task',    emoji:'💧', title:'Irrigation Check – Rice',              notes:'Ensure 5–7 cm standing water.' },
    { offset:14, type:'task',    emoji:'🌿', title:'First Weeding',                        notes:'Manual or chemical weed control.' },
    { offset:21, type:'task',    emoji:'🧪', title:'Fertilizer – Urea (1st application)', notes:'1 bag urea/ha top-dress.' },
    { offset:35, type:'task',    emoji:'🌿', title:'Second Weeding',                       notes:'Spot weed if needed.' },
    { offset:40, type:'pest',    emoji:'🐛', title:'Pest Alert: Brown Planthopper Risk',   notes:'Monitor fields closely. Use IPM.' },
    { offset:45, type:'task',    emoji:'🧪', title:'Fertilizer – Urea (2nd application)', notes:'Apply at panicle initiation stage.' },
    { offset:60, type:'pest',    emoji:'🐛', title:'Pest Alert: Blast Disease Risk',       notes:'Apply fungicide if blast symptoms appear.' },
    { offset:75, type:'task',    emoji:'💧', title:'Irrigation – Drain Field',             notes:'Stop irrigation 2 weeks before harvest.' },
    { offset:90, type:'harvest', emoji:'🌾', title:'Estimated Harvest – Rice',             notes:'Harvest when 80–85% of grains are golden.' }
  ],
  corn: [
    { offset:0,  type:'task',    emoji:'🌽', title:'Corn Planting Day',           notes:'Plant 2 seeds per hill, 75cm x 25cm spacing.' },
    { offset:10, type:'task',    emoji:'🌿', title:'Thinning / Gap Filling',       notes:'Retain 1 healthy plant per hill.' },
    { offset:21, type:'task',    emoji:'🧪', title:'Fertilizer – Urea (1st)',      notes:'Side-dress after full emergence.' },
    { offset:30, type:'task',    emoji:'🌿', title:'Weeding – Corn Field',         notes:'Critical before canopy closes.' },
    { offset:35, type:'task',    emoji:'🌽', title:'Hilling-Up',                   notes:'Cultivate soil around stem base.' },
    { offset:45, type:'task',    emoji:'🧪', title:'Fertilizer – Complete (2nd)',  notes:'Apply at tasseling stage.' },
    { offset:50, type:'pest',    emoji:'🐛', title:'Pest Alert: Armyworm Season', notes:'Scout fields daily.' },
    { offset:75, type:'harvest', emoji:'🌽', title:'Estimated Harvest – Corn',    notes:'Harvest when husks are dry and kernels are firm.' }
  ],
  vegetables: [
    { offset:0,  type:'task',    emoji:'🥬', title:'Vegetable Planting Day',          notes:'Prepare raised beds. Transplant in early morning.' },
    { offset:5,  type:'task',    emoji:'💧', title:'Irrigation – Seedlings',          notes:'Water lightly twice daily.' },
    { offset:10, type:'task',    emoji:'🌿', title:'First Weeding',                   notes:'Hand-pull weeds close to plants.' },
    { offset:14, type:'task',    emoji:'🧪', title:'Foliar Spray (1st)',              notes:'Apply balanced foliar fertilizer.' },
    { offset:21, type:'pest',    emoji:'🐛', title:'Pest Scouting Week',              notes:'Check for aphids, caterpillars, mildew.' },
    { offset:30, type:'harvest', emoji:'🥬', title:'Estimated Harvest – Vegetables', notes:'Leafy vegetables ready in 30–45 days.' }
  ],
  banana: [
    { offset:0,   type:'task',    emoji:'🍌', title:'Banana Sucker Planting',           notes:'Use sword suckers. 3m x 3m spacing.' },
    { offset:30,  type:'task',    emoji:'🧪', title:'Fertilizer – Complete (1st)',      notes:'Apply around base.' },
    { offset:60,  type:'task',    emoji:'🌿', title:'Desuckering',                      notes:'Keep 2–3 suckers per mat.' },
    { offset:90,  type:'task',    emoji:'🧪', title:'Fertilizer – Potash (2nd)',        notes:'Potassium improves fruit quality.' },
    { offset:180, type:'pest',    emoji:'🐛', title:'Pest Alert: Bunchy Top / Weevil', notes:'Monitor for stunted growth.' },
    { offset:270, type:'harvest', emoji:'🍌', title:'Estimated Harvest – Banana',      notes:'9–12 months after planting.' }
  ],
  cassava: [
    { offset:0,   type:'task',    emoji:'🍠', title:'Cassava Stem Planting',      notes:'Use 25–30cm stem cuttings at 45° angle.' },
    { offset:30,  type:'task',    emoji:'🌿', title:'First Weeding',              notes:'Critical in first 3 months.' },
    { offset:45,  type:'task',    emoji:'🧪', title:'Fertilizer – Urea+Potash',   notes:'Apply NPK. Side-dress and cover.' },
    { offset:90,  type:'task',    emoji:'🌿', title:'Second Weeding & Hilling',   notes:'Control weeds, hill up around base.' },
    { offset:120, type:'pest',    emoji:'🐛', title:'Pest Alert: Mealybug/Mites', notes:'Inspect leaf undersides.' },
    { offset:270, type:'harvest', emoji:'🍠', title:'Estimated Harvest – Cassava', notes:'9–12 months. Tubers ready when leaves yellow.' }
  ],
  sweetPotato: [
    { offset:0,  type:'task',    emoji:'🍠', title:'Sweet Potato Vine Planting',      notes:'Plant 25–30cm vine tips on ridges.' },
    { offset:21, type:'task',    emoji:'🌿', title:'Weeding & Vine Flipping',         notes:'Remove weeds; flip vines to stop ground-rooting.' },
    { offset:30, type:'task',    emoji:'🧪', title:'Fertilizer – Potassium',          notes:'Avoid excess nitrogen.' },
    { offset:45, type:'pest',    emoji:'🐛', title:'Pest Alert: Sweet Potato Weevil', notes:'Check soil level for weevil damage.' },
    { offset:90, type:'harvest', emoji:'🍠', title:'Estimated Harvest – Kamote',      notes:'3–4 months. Harvest when leaves yellow.' }
  ],
  coconut: [
    { offset:0,    type:'task',    emoji:'🥥', title:'Coconut Seedling Planting',     notes:'9m x 9m triangular spacing.' },
    { offset:90,   type:'task',    emoji:'🌿', title:'Circle Weeding',                notes:'Keep 1m radius around each tree weed-free.' },
    { offset:120,  type:'task',    emoji:'🧪', title:'Fertilizer – Complete (1st)',   notes:'500g urea, 500g rock phosphate per tree.' },
    { offset:270,  type:'pest',    emoji:'🐛', title:'Pest Alert: Rhinoceros Beetle', notes:'Use beetle traps and biological control.' },
    { offset:365,  type:'task',    emoji:'🧪', title:'Fertilizer – Annual',           notes:'Apply during rainy season.' },
    { offset:1460, type:'harvest', emoji:'🥥', title:'First Commercial Harvest',      notes:'4–5 years after planting.' }
  ]
};

function generateCropLifecycle(plantingDateKey, cropType, baseTitle) {
  const schedule = cropSchedules[cropType];
  if (!schedule) return [];
  const plantDate   = new Date(plantingDateKey+'T00:00:00');
  const lifecycleId = `lc_${Date.now()}_${cropType}`;
  return schedule.map((step, i) => ({
    id:            `${Date.now()}_${i}_${Math.floor(Math.random()*99999)}`,
    dateKey:       getDateKey(addDays(plantDate, step.offset)),
    type:          step.type,
    formType:      step.type==='harvest' ? 'harvest' : step.type==='pest' ? 'pestControl' : 'planting',
    emoji:         step.emoji,
    title:         step.title,
    notes:         step.notes || `Auto-generated from: "${baseTitle}"`,
    crop:          cropType,
    autoGenerated: true,
    lifecycleId,
    sourceTitle:   baseTitle
  }));
}

// ======================================================================
// SECTION: RECURRING MARKET DAYS
// ======================================================================

function initRecurringMarketDays() {
  calendarEvents = calendarEvents.filter(e => typeof e.id === 'number');
  const today   = new Date(); today.setHours(0,0,0,0);
  const endDate = addDays(today, 365);

  // Bi-weekly Saturday market
  let sat = new Date(today);
  while (sat.getDay() !== 6) sat = addDays(sat, 1);
  while (sat <= endDate) {
    calendarEvents.push({ id:`market_${getDateKey(sat)}`, dateKey:getDateKey(sat), type:'market', formType:'marketDay', emoji:'🛒', title:'Oroquieta Public Market Day', notes:'Best prices for livestock & produce.', location:'Oroquieta City Market', recurrent:true, autoGenerated:true });
    sat = addDays(sat, 14);
  }

  // Monthly Sunday livestock trading
  let sun = new Date(today);
  while (sun.getDay() !== 0) sun = addDays(sun, 1);
  while (sun <= endDate) {
    calendarEvents.push({ id:`trade_${getDateKey(sun)}`, dateKey:getDateKey(sun), type:'market', formType:'marketDay', emoji:'🐄', title:'Livestock Trading Post', notes:'Monthly livestock barter.', location:'Oroquieta Trading Post', recurrent:true, autoGenerated:true });
    sun = addDays(sun, 28);
  }
}

// ======================================================================
// SECTION: ACTIVE EVENTS HELPER
// ======================================================================

function getActiveEvents() {
  return calendarMode === 'community' ? communityEvents : calendarEvents;
}

function updateCalendarTitle() {
  const titleEl    = document.getElementById('calendarTitle');
  const subtitleEl = document.getElementById('calendarSubtitle');
  const displayName = accountName || 'My Farm';
  if (titleEl) {
    titleEl.innerHTML = `<i class="fas fa-seedling"></i> ${displayName}'s Calendar`;
  }
  if (subtitleEl) {
    subtitleEl.textContent = `Welcome back, ${displayName.split(' ')[0] || displayName}`;
  }
}

// ======================================================================
// SECTION: INITIALIZATION
// ======================================================================

document.addEventListener('DOMContentLoaded', async () => {
  loadFromLocalStorage();
  initRecurringMarketDays();
  const profileNameEl = document.querySelector('.profile-name');
  if (profileNameEl) {
    accountName = profileNameEl.textContent.trim() || accountName;
  }
  updateCalendarTitle();

  // Initialize avatar initials (from accountName) so avatar isn't a blank green circle
  const avatarEl = document.getElementById('avatarBtn') || document.querySelector('.nav-avatar');
  if (avatarEl) {
    const initials = (accountName || 'U').split(' ').map(n => n[0] || '').join('').slice(0,2).toUpperCase();
    avatarEl.textContent = initials;
    if (window.initUserDropdown) {
      initUserDropdown({
        avatarBtnId: 'avatarBtn',
        dropdownId: 'profileDropdown',
        user: {
          name: accountName,
          role: 'DA Verified Farmer',
          initials
        },
        onAction: action => {
          if (action === 'logout') showToast('👋 Signed out');
        }
      });
    }
  }

  if (window.initNotifications) {
    initNotifications({ fakeData: true });
  }

  // Ensure header layer icon buttons reflect `activeLayers` on initial load
  Object.keys(activeLayers).forEach(k => {
    try {
      const btnId = 'layer' + k.charAt(0).toUpperCase() + k.slice(1);
      const el = document.getElementById(btnId);
      if (el) el.classList.toggle('active', !!activeLayers[k]);
    } catch (e) { /* ignore */ }
  });
  renderCalendar();
  renderMiniCalendar();
  await renderWeather();
  renderStats();
  renderUpcoming();
  renderDaEvents();
  renderLifecycleProgress();
  document.getElementById('eventDate').value = getDateKey(new Date());

  // Close modals when clicking their backdrop or a .close-modal button
  document.addEventListener('click', e => {
    if (e.target.classList.contains('modal')) e.target.classList.add('hidden');
    const closeBtn = e.target.closest('.close-modal');
    if (closeBtn) {
      const modal = closeBtn.closest('.modal');
      if (modal) modal.classList.add('hidden');
      e.stopPropagation();
    }
  });
});

// ======================================================================
// SECTION: PROFILE DROPDOWN (matches TanimBase)
// ======================================================================

function toggleProfile() {
  document.getElementById('profile-dropdown').classList.toggle('open');
  document.getElementById('profile-overlay').classList.toggle('open');
}

// ======================================================================
// SECTION: WEATHER RENDER
// ======================================================================

async function renderWeather() {
  const data = await fetchWeatherFromPAGASA();
  const dailyRain = {};
  if (data.forecast) data.forecast.forEach(f => { if (f.dateKey) dailyRain[f.dateKey] = parseInt(f.rain) || 0; });
  weatherCache = { data, dailyRain };
  renderCalendar();
}

// ======================================================================
// SECTION: STATS STRIP
// ======================================================================

function renderStats() {
  const strip  = document.getElementById('statsStrip');
  const current = weatherCache?.data?.current;
  const today = getDateKey(new Date());
  const forecastToday = weatherCache?.data?.forecast?.find(f => f.dateKey === today);
  if (!current && !forecastToday) {
    strip.innerHTML = `<div class="weather-card"><div class="wday">No weather data</div><div class="wdesc">Waiting for forecast...</div></div>`;
    return;
  }
  const icon = current?.icon || forecastToday?.icon || '☀️';
  const label = current?.condition || (forecastToday ? 'Forecast' : 'Weather');
  const temp = current ? `${current.temp}°C` : `${forecastToday.high}° / ${forecastToday.low}°`;
  const detail = current ? `💧 ${current.humidity}% • 🌬️ ${current.wind}` : forecastToday ? `🌧 ${forecastToday.rain}` : '';
  strip.innerHTML = `
    <div class="weather-card">
      <div class="wday">Today</div>
      <div class="wicon">${icon}</div>
      <div class="wtemps">${temp}</div>
      <div class="wdesc">${label}</div>
      <div class="wrain">${detail}</div>
    </div>`;
}

// ======================================================================
// SECTION: CALENDAR GRID RENDER
// ======================================================================

function renderCalendar() {
  const grid       = document.getElementById('calendarGrid');
  const monthNames = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  document.getElementById('monthName').textContent = monthNames[currentMonth];
  document.getElementById('yearName').textContent  = currentYear;

  const today       = new Date();
  const firstDay    = new Date(currentYear, currentMonth, 1).getDay();
  const daysInMonth = new Date(currentYear, currentMonth+1, 0).getDate();
  const daysInPrev  = new Date(currentYear, currentMonth, 0).getDate();
  const events      = getActiveEvents();

  // Build lifecycle stripe date ranges
  const lifecycleMap = {};
  events.forEach(e => {
    if (!e.lifecycleId) return;
    if (!lifecycleMap[e.lifecycleId]) lifecycleMap[e.lifecycleId] = { min: e.dateKey, max: e.dateKey };
    if (e.dateKey < lifecycleMap[e.lifecycleId].min) lifecycleMap[e.lifecycleId].min = e.dateKey;
    if (e.dateKey > lifecycleMap[e.lifecycleId].max) lifecycleMap[e.lifecycleId].max = e.dateKey;
  });

  let html = '';

  for (let i = 0; i < firstDay; i++) {
    html += `<div class="cal-day other-month"><div class="cal-date">${daysInPrev - firstDay + 1 + i}</div></div>`;
  }

  for (let day = 1; day <= daysInMonth; day++) {
    const cellDate  = new Date(currentYear, currentMonth, day);
    const dateKey   = getDateKey(cellDate);
    const isToday   = day === today.getDate() && currentMonth === today.getMonth() && currentYear === today.getFullYear();
    const isWeekend = cellDate.getDay() === 0 || cellDate.getDay() === 6;

    const dayEvents = events.filter(e => {
      if (e.dateKey !== dateKey) return false;
      if (calendarMode === 'community') return true;
      if (e.type === 'task' || e.type === 'harvest' || e.type === 'pest') return activeLayers.tasks;
      if (e.type === 'da')     return activeLayers.da;
      if (e.type === 'market') return activeLayers.market;
      return false;
    });

    const dots = dayEvents.slice(0, 4).map(e => {
      const cls = e.type==='da' ? 'dot-da' : e.type==='market' ? 'dot-market' : e.type==='harvest' ? 'dot-harvest' : e.type==='pest' ? 'dot-pest' : 'dot-task';
      return `<div class="cal-dot ${cls}" title="${e.title}"></div>`;
    }).join('') + (dayEvents.length > 4 ? `<div class="cal-dot-more">+${dayEvents.length - 4}</div>` : '');

    let label = '';
    if (dayEvents.length > 0) {
      const f  = dayEvents[0];
      const lc = f.type==='da' ? 'label-da' : f.type==='market' ? 'label-market' : f.type==='harvest' ? 'label-harvest' : f.type==='pest' ? 'label-pest' : 'label-task';
      label = `<div class="cal-event-label ${lc}">${f.emoji} ${f.title}</div>`;
    }

    const moon = activeLayers.moon
      ? `<div class="cal-moon" title="${getMoonPhaseName(cellDate)}">${getMoonPhase(cellDate)}</div>` : '';

    let weatherDot = '';
    if (activeLayers.weather) {
      const rain = weatherCache?.dailyRain?.[dateKey];
      if (rain !== undefined && rain >= 50) {
        weatherDot = `<div class="cal-dot dot-weather" title="Rain: ${rain}%" style="background:${rain>=80?'#e74c3c':'#3498db'}"></div>`;
      }
    }

    const stripe = calendarMode === 'personal' && Object.values(lifecycleMap).some(lc => dateKey >= lc.min && dateKey <= lc.max)
      ? '<div class="lifecycle-stripe"></div>' : '';

    const farmerBadge = calendarMode === 'community' && dayEvents.length > 0
      ? `<div class="community-farmer-badge">${dayEvents[0].farmer || ''}</div>` : '';

    const density = dayEvents.length === 0 ? '' : dayEvents.length <= 2 ? 'heat-low' : dayEvents.length <= 4 ? 'heat-mid' : 'heat-high';

    html += `
      <div class="cal-day ${isToday?'today':''} ${isWeekend?'weekend':''} ${density}"
           onclick="handleDayClick('${dateKey}')" title="${formatDateLabel(dateKey)}">
        <div class="cal-date">${day}</div>
        ${stripe}
        <div class="cal-dots">${dots}${weatherDot}</div>
        ${label}${moon}${farmerBadge}
      </div>`;
  }

  const trailing = 42 - (firstDay + daysInMonth);
  for (let i = 1; i <= trailing; i++) html += `<div class="cal-day other-month"><div class="cal-date">${i}</div></div>`;

  grid.innerHTML = html;
}

// ======================================================================
// SECTION: MONTH NAVIGATION
// ======================================================================

function prevMonth() { currentMonth--; if (currentMonth < 0)  { currentMonth = 11; currentYear--; } renderCalendar(); renderStats(); renderUpcoming(); renderDaEvents(); renderMiniCalendar(); }
function nextMonth() { currentMonth++; if (currentMonth > 11) { currentMonth = 0;  currentYear++; } renderCalendar(); renderStats(); renderUpcoming(); renderDaEvents(); renderMiniCalendar(); }
function goToToday() {
  const now = new Date(); currentMonth = now.getMonth(); currentYear = now.getFullYear();
  renderCalendar(); renderStats(); renderUpcoming(); renderDaEvents();
  showToast('📅 Back to today');
}

// ======================================================================
// SECTION: LAYER TOGGLE
// ======================================================================

function toggleLayer(layerKey, chipElement) {
  activeLayers[layerKey] = !activeLayers[layerKey];
  chipElement.classList.toggle('active', activeLayers[layerKey]);
  if (layerKey === 'weather') {
    const isLive = weatherCache?.data?.live;
    showToast(isLive ? '🌤️ Live weather from Open-Meteo • Oroquieta City' : '⚠️ Weather is simulated — check your connection');
  }
  renderCalendar();
}

// ======================================================================
// SECTION: UPCOMING PANEL
// ======================================================================

function renderUpcoming() {
  const list  = document.getElementById('upcomingList');
  const panel = document.querySelector('.upcoming-panel h3');
  const today = new Date(); today.setHours(0,0,0,0);
  const isNow = currentMonth === today.getMonth() && currentYear === today.getFullYear();
  const mons  = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  if (panel) panel.innerHTML = isNow ? '<i class="fas fa-list-ul"></i> Upcoming This Week' : `<i class="fas fa-list-ul"></i> Events in ${mons[currentMonth]}`;

  let evs;
  if (isNow) {
    evs = getActiveEvents().filter(e => { const d = getDaysUntil(e.dateKey); return d >= 0 && d <= 7; }).sort((a,b) => a.dateKey.localeCompare(b.dateKey));
  } else {
    const s = `${currentYear}-${String(currentMonth+1).padStart(2,'0')}-01`;
    const e = getDateKey(new Date(currentYear, currentMonth+1, 0));
    evs = getActiveEvents().filter(ev => ev.dateKey >= s && ev.dateKey <= e).sort((a,b) => a.dateKey.localeCompare(b.dateKey));
  }

  list.innerHTML = evs.length === 0
    ? `<p style="color:#888;font-size:13px;padding:8px 0">${isNow ? 'No events in the next 7 days.' : 'No events this month yet.'}</p>`
    : evs.map(e => {
        const diff  = getDaysUntil(e.dateKey);
        const label = diff === 0 ? 'Today' : diff === 1 ? 'Tmrw' : diff > 0 ? `${diff}d` : formatDateLabel(e.dateKey).split(',')[1]?.trim() || '';
        return `<div class="upcoming-item" onclick="openDayDetail('${e.dateKey}')">
          <div class="upcoming-icon">${e.emoji}</div>
          <div class="upcoming-body">
            <div class="upcoming-title">${e.title}</div>
            <div class="upcoming-meta">${formatDateLabel(e.dateKey)}${e.location ? ' • ' + e.location : ''}</div>
          </div>
          <div class="upcoming-date-badge">${label}</div>
        </div>`;
      }).join('');
}

// ======================================================================
// SECTION: DA EVENTS PANEL
// ======================================================================

function renderDaEvents() {
  const list  = document.getElementById('daEventsList');
  const panel = document.querySelector('.da-panel h3');
  const today = new Date(); today.setHours(0,0,0,0);
  const isNow = currentMonth === today.getMonth() && currentYear === today.getFullYear();
  const mons  = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  if (panel) panel.innerHTML = isNow ? '<i class="fas fa-landmark"></i> DA Community Resources' : `<i class="fas fa-landmark"></i> DA Events — ${mons[currentMonth]}`;

  let items;
  if (isNow) {
    items = getActiveEvents().filter(e => e.type === 'da').sort((a,b) => a.dateKey.localeCompare(b.dateKey)).slice(0, 6);
  } else {
    const s = `${currentYear}-${String(currentMonth+1).padStart(2,'0')}-01`;
    const e = getDateKey(new Date(currentYear, currentMonth+1, 0));
    items = getActiveEvents().filter(ev => ev.type === 'da' && ev.dateKey >= s && ev.dateKey <= e).sort((a,b) => a.dateKey.localeCompare(b.dateKey));
  }

  list.innerHTML = items.length === 0
    ? `<p style="color:#888;font-size:13px">No DA events ${isNow ? 'scheduled yet.' : 'this month.'}</p>`
    : items.map(e => `
        <div class="da-event-item" onclick="openDayDetail('${e.dateKey}')">
          <div class="da-event-icon">${e.emoji}</div>
          <div class="da-event-body">
            <div class="da-event-title">${e.title}</div>
            <div class="da-event-date">${formatDateLabel(e.dateKey)}${e.location ? ' • ' + e.location : ''}</div>
          </div>
          <div class="da-event-badge">${getDaysUntil(e.dateKey) >= 0 ? getDaysUntil(e.dateKey) + 'd' : 'Past'}</div>
        </div>`).join('');
}

// ======================================================================
// SECTION: DAY DETAIL MODAL
// ======================================================================

function handleDayClick(dateKey) {
  const evs = getActiveEvents().filter(e => e.dateKey === dateKey);
  if (evs.length === 0 && calendarMode === 'personal') openAddEventModalForDay(dateKey);
  else openDayDetail(dateKey);
}

function openDayDetail(dateKey) {
  const modal   = document.getElementById('dayDetailModal');
  const content = document.getElementById('dayDetailContent');
  const dayDate = new Date(dateKey+'T00:00:00');
  const isToday = dateKey === getDateKey(new Date());
  const dayEvs  = getActiveEvents().filter(e => e.dateKey === dateKey);
  const months  = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  const dow     = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
  const tips    = ['Jan: Dry season — good for corn planting.','Feb: Prepare rice seedbeds.','Mar: Ideal for vegetable planting.','Apr: Watch for heat stress.','May: Transplant rice. Rainy season begins.','Jun: Monitor for fungal disease.','Jul: Weed control critical.','Aug: Watch for brown planthopper.','Sep: Begin corn harvest.','Oct: Wet-season rice harvest.','Nov: Plant dry-season corn.','Dec: Market season peaks.'];

  const eventsHTML = dayEvs.length === 0
    ? `<p style="color:#888;font-size:14px;padding:8px 0">No events for this day. Tap + to add one.</p>`
    : dayEvs.map(e => {
        const dc      = e.type==='da' ? 'dot-da' : e.type==='market' ? 'dot-market' : e.type==='harvest' ? 'dot-harvest' : e.type==='pest' ? 'dot-pest' : 'dot-task';
        const autoTag = e.autoGenerated ? '<span style="font-size:10px;color:#aaa;margin-left:6px;background:#f0f0f0;padding:1px 5px;border-radius:4px">auto</span>' : '';
        const actions = calendarMode === 'personal'
          ? `<div style="display:flex;gap:4px;flex-shrink:0;">
               <button onclick="openEditEventModal('${e.id}')" style="background:none;border:1px solid #ddd;border-radius:6px;padding:4px 8px;font-size:11px;cursor:pointer;color:#555;">✏️ Edit</button>
               <button onclick="deleteEvent('${e.id}')" style="background:none;border:1px solid #fcc;border-radius:6px;padding:4px 8px;font-size:11px;cursor:pointer;color:#c00;">🗑️</button>
             </div>` : '';
        return `<div class="day-event-row">
          <div class="day-event-dot ${dc}"></div>
          <div class="day-event-info">
            <div class="day-event-title">${e.emoji} ${e.title}${autoTag}</div>
            ${e.notes    ? `<div class="day-event-sub">📝 ${e.notes}</div>` : ''}
            ${e.location ? `<div class="day-event-sub">📍 ${e.location}</div>` : ''}
            ${e.crop     ? `<div class="day-event-sub">🌱 Crop: ${e.crop}</div>` : ''}
            ${e.farmer   ? `<div class="day-event-sub">👨‍🌾 ${e.farmer}</div>` : ''}
          </div>
          ${actions}
        </div>`;
      }).join('');

  const wf = weatherCache?.data?.forecast?.find(f => f.dateKey === dateKey);
  const weatherHTML = wf
    ? `<div class="day-weather-box"><span style="font-size:26px">${wf.icon}</span><div><strong>Forecast</strong><br><span style="font-size:12px;color:#555">High: ${wf.high}°C • Low: ${wf.low}°C • 🌧️ <span style="color:${parseInt(wf.rain)>=60?'#e74c3c':'#3498db'};font-weight:700">${wf.rain} rain</span></span></div></div>`
    : `<div class="day-weather-box"><span style="font-size:26px">🌤️</span><div><strong>Weather</strong><br><span style="font-size:12px;color:#888">Outside 7-day forecast window</span></div></div>`;

  content.innerHTML = `
    <div class="day-detail-header">
      <div class="day-detail-date-num">${dayDate.getDate()}</div>
      <div>
        <div style="font-weight:700;font-size:16px;color:var(--primary)">
          ${dow[dayDate.getDay()]}, ${months[dayDate.getMonth()]} ${dayDate.getFullYear()}
          ${isToday ? '<span style="background:var(--accent);color:white;font-size:11px;padding:2px 8px;border-radius:10px;margin-left:6px">Today</span>' : ''}
        </div>
        <div class="day-detail-date-text">Moon: ${getMoonPhase(dayDate)} ${getMoonPhaseName(dayDate)}</div>
      </div>
    </div>
    <div class="day-tip-bar"><i class="fas fa-lightbulb"></i><span>${tips[dayDate.getMonth()]}</span></div>
    ${eventsHTML}
    ${weatherHTML}
    ${calendarMode === 'personal' ? `<div style="margin-top:14px;display:flex;justify-content:flex-end"><button onclick="openAddEventModalForDay('${dateKey}')" class="btn primary"><i class="fas fa-plus"></i> Add Event for this Day</button></div>` : ''}`;

  modal.classList.remove('hidden');
  if (dayEvs.some(e => e.type === 'harvest')) setTimeout(triggerConfetti, 250);
}

function closeDayDetailModal() {
  document.getElementById('dayDetailModal').classList.add('hidden');
}

// ======================================================================
// SECTION: DELETE EVENT
// ======================================================================

function deleteEvent(eventId) {
  const event = calendarEvents.find(e => String(e.id) === String(eventId));
  if (!event) return;
  if (event.lifecycleId) {
    const grp = calendarEvents.filter(e => e.lifecycleId === event.lifecycleId);
    if (grp.length > 1 && confirm(`This event belongs to a ${event.crop || 'crop'} lifecycle (${grp.length} tasks).\n\nOK = delete all ${grp.length} events\nCancel = delete only this one`)) {
      deleteLifecycle(event.lifecycleId); return;
    }
  }
  historyStack.push({ action: 'addEvents', events: [event] }); redoStack = [];
  calendarEvents  = calendarEvents.filter(e => String(e.id) !== String(eventId));
  communityEvents = communityEvents.filter(e => String(e.id) !== `pub_${eventId}`);
  saveToLocalStorage();
  closeDayDetailModal();
  renderCalendar(); renderStats(); renderUpcoming(); renderDaEvents(); renderLifecycleProgress();
  showToast('🗑️ Event deleted (Ctrl+Z to undo)');
}

function deleteLifecycle(lifecycleId) {
  const toDelete = calendarEvents.filter(e => e.lifecycleId === lifecycleId);
  if (!toDelete.length) return;
  historyStack.push({ action: 'addEvents', events: toDelete }); redoStack = [];
  calendarEvents = calendarEvents.filter(e => e.lifecycleId !== lifecycleId);
  toDelete.forEach(e => { communityEvents = communityEvents.filter(c => String(c.id) !== `pub_${e.id}`); });
  saveToLocalStorage();
  closeDayDetailModal();
  renderCalendar(); renderStats(); renderUpcoming(); renderDaEvents(); renderLifecycleProgress();
  showToast(`🗑️ ${toDelete.length} lifecycle events deleted (Ctrl+Z to undo)`);
}

// ======================================================================
// SECTION: ADD / EDIT EVENT MODAL
// ======================================================================

function openAddEventModal() {
  const modal = document.getElementById('addEventModal');
  delete modal.dataset.editingId;
  modal.querySelector('h3').innerHTML = '<i class="fas fa-plus-circle" style="color:var(--calendar-green)"></i> Add Calendar Event';
  modal.classList.remove('hidden');
}

function openAddEventModalForDay(dateKey) {
  closeDayDetailModal();
  document.getElementById('eventDate').value = dateKey;
  openAddEventModal();
}

function closeAddEventModal() {
  const modal = document.getElementById('addEventModal');
  delete modal.dataset.editingId;
  modal.classList.add('hidden');
}

function onEventTypeChange() {
  const type     = document.getElementById('eventType').value;
  const cropGrp  = document.getElementById('cropGroup');
  const notice   = document.getElementById('autoTasksNotice');
  const recGrp   = document.getElementById('recurrenceGroup');
  cropGrp.style.display = ['planting','harvest','fertilizer','weeding','pestControl'].includes(type) ? '' : 'none';
  notice.classList.toggle('hidden', type !== 'planting');
  if (recGrp) recGrp.style.display = type === 'planting' ? 'none' : '';
}

function openEditEventModal(eventId) {
  const event = calendarEvents.find(e => String(e.id) === String(eventId));
  if (!event) return;
  closeDayDetailModal();
  const reverseMap = { task:'note', harvest:'harvest', pest:'pestControl', da:'daEvent', market:'marketDay' };
  const formType   = event.formType || reverseMap[event.type] || 'note';
  const typeEl = document.getElementById('eventType');
  if (typeEl) { typeEl.value = formType; onEventTypeChange(); }
  const cropEl = document.getElementById('eventCrop');
  if (cropEl && event.crop) cropEl.value = event.crop;
  document.getElementById('eventTitle').value    = event.title.replace(/\s@\s\d{2}:\d{2}$/, '');
  document.getElementById('eventDate').value     = event.dateKey || '';
  document.getElementById('eventLocation').value = event.location || '';
  document.getElementById('eventNotes').value    = event.notes || '';
  const modal = document.getElementById('addEventModal');
  modal.dataset.editingId = eventId;
  modal.querySelector('h3').innerHTML = '<i class="fas fa-edit" style="color:var(--calendar-green)"></i> Edit Calendar Event';
  modal.classList.remove('hidden');
}

function submitEvent() {
  const modal      = document.getElementById('addEventModal');
  const editingId  = modal.dataset.editingId || null;
  const type       = document.getElementById('eventType').value;
  const title      = document.getElementById('eventTitle').value.trim();
  const dateKey    = document.getElementById('eventDate').value;
  const time       = document.getElementById('eventTime').value;
  const location   = document.getElementById('eventLocation').value.trim();
  const notes      = document.getElementById('eventNotes').value.trim();
  const crop       = document.getElementById('eventCrop')?.value || '';
  const isPublic   = document.getElementById('eventIsPublic')?.checked || false;
  const recurrence = document.getElementById('eventRecurrence')?.value || 'none';

  if (!type)    { showToast('⚠️ Please select an event type'); showFieldError('eventType'); return; }
  if (!title)   { showToast('⚠️ Please enter an event title'); showFieldError('eventTitle'); return; }
  if (!dateKey) { showToast('⚠️ Please select a date');        showFieldError('eventDate'); return; }

  if (editingId !== null) {
    const idx = calendarEvents.findIndex(e => String(e.id) === String(editingId));
    if (idx !== -1) {
      const ex      = calendarEvents[idx];
      const updated = { ...ex, type: mapFormTypeToInternal(type), formType: type, emoji: getEmojiForType(type), title: title + (time ? ` @ ${time}` : ''), notes: notes || ex.notes, location: location || ex.location, crop: crop || ex.crop, dateKey, autoGenerated: ex.autoGenerated };
      historyStack.push({ action: 'editEvent', eventId: String(ex.id), before: { ...ex }, after: updated }); redoStack = [];
      calendarEvents[idx] = updated;
      saveToLocalStorage();
      showToast('✅ Event updated! (Ctrl+Z to undo)');
    }
    resetAndClose(); return;
  }

  const newEvent = { id: String(Date.now()), dateKey, type: mapFormTypeToInternal(type), formType: type, emoji: getEmojiForType(type), title: title + (time ? ` @ ${time}` : ''), notes: notes || undefined, location: location || undefined, crop: crop || undefined, autoGenerated: false, isPublic };
  let added = [newEvent];

  if (type === 'planting' && crop && cropSchedules[crop]) {
    const lc = generateCropLifecycle(dateKey, crop, title);
    if (isPublic) lc.forEach(e => { e.isPublic = true; e.farmer = 'Kuya Mario S.'; });
    added = lc;
    showToast(`✅ Planting day added! ${lc.length} tasks auto-scheduled.`);
  } else if (recurrence !== 'none') {
    added = generateRecurringInstances(newEvent, recurrence);
    showToast(`✅ ${added.length} recurring events added!`);
  } else {
    showToast(isPublic ? '✅ Event added & posted to Community!' : '✅ Event added!');
  }

  historyStack.push({ action: 'addEvents', events: added }); redoStack = [];
  calendarEvents.push(...added);
  saveToLocalStorage();

  if (isPublic) {
    added.forEach(e => {
      if (!communityEvents.some(c => c.id === `pub_${e.id}`))
        communityEvents.unshift({ ...e, id: `pub_${e.id}`, farmer: 'Kuya Mario S.' });
    });
    showToast('📢 Posted to Community Calendar!');
  }
  resetAndClose();
}

function mapFormTypeToInternal(type) {
  return { planting:'task', harvest:'harvest', fertilizer:'task', weeding:'task', pestControl:'pest', irrigation:'task', vaccination:'task', daEvent:'da', marketDay:'market', note:'task' }[type] || 'task';
}
function getEmojiForType(type) {
  return { planting:'🌱', harvest:'🌾', fertilizer:'🧪', weeding:'🌿', pestControl:'🐛', irrigation:'💧', vaccination:'💉', daEvent:'🏛️', marketDay:'🛒', note:'📝' }[type] || '📅';
}

function resetAndClose() {
  renderCalendar(); renderStats(); renderUpcoming(); renderDaEvents(); renderLifecycleProgress();
  closeAddEventModal();
  ['eventType','eventTitle','eventNotes','eventLocation','eventTime'].forEach(id => { const el = document.getElementById(id); if (el) el.value = ''; });
  const recEl = document.getElementById('eventRecurrence'); if (recEl) recEl.value = 'none';
  document.getElementById('cropGroup').style.display = 'none';
  document.getElementById('autoTasksNotice').classList.add('hidden');
  document.getElementById('eventDate').value = getDateKey(new Date());
}

// ======================================================================
// SECTION: WEATHER DETAIL MODAL
// ======================================================================

function openWeatherDetail(day, icon, high, low, rain) {
  document.getElementById('weatherDetailContent').innerHTML = `
    <div style="text-align:center;padding:16px 0">
      <div style="font-size:52px">${icon}</div>
      <div style="font-size:28px;font-weight:800;color:var(--calendar-sky)">${high}°C / ${low}°C</div>
      <div style="font-size:15px;color:#555;margin:8px 0">${day}</div>
      <div style="font-size:14px;color:var(--calendar-sky);margin-top:8px">💧 Rain probability: <strong>${rain}</strong></div>
      <div style="font-size:13px;color:#888;margin-top:16px;line-height:1.6">
        ${parseFloat(rain) > 60 ? '⚠️ High rain chance. Consider delaying fertilizer or field work.' : '✅ Good conditions for field work.'}
      </div>
    </div>`;
  document.getElementById('weatherDetailModal').classList.remove('hidden');
}

function closeWeatherDetailModal() {
  document.getElementById('weatherDetailModal').classList.add('hidden');
}

// ======================================================================
// SECTION: UNDO / REDO
// ======================================================================

function undoLastAction() {
  if (!historyStack.length) { showToast('Nothing to undo'); return; }
  const last = historyStack.pop(); redoStack.push(last);
  if (last.action === 'addEvents') {
    const ids = new Set(last.events.map(e => String(e.id)));
    calendarEvents = calendarEvents.filter(e => !ids.has(String(e.id)));
    saveToLocalStorage(); renderCalendar(); renderStats(); renderUpcoming(); renderDaEvents(); renderLifecycleProgress();
    showToast(`↩️ ${last.events.length} event(s) removed`);
  } else if (last.action === 'editEvent') {
    const idx = calendarEvents.findIndex(e => String(e.id) === last.eventId);
    if (idx !== -1) calendarEvents[idx] = last.before;
    saveToLocalStorage(); renderCalendar(); renderStats(); renderUpcoming(); renderDaEvents(); renderLifecycleProgress();
    showToast('↩️ Edit undone');
  }
}

function redoLastAction() {
  if (!redoStack.length) { showToast('Nothing to redo'); return; }
  const last = redoStack.pop(); historyStack.push(last);
  if (last.action === 'addEvents') {
    calendarEvents.push(...last.events);
    saveToLocalStorage(); renderCalendar(); renderStats(); renderUpcoming(); renderDaEvents(); renderLifecycleProgress();
    showToast(`↪️ ${last.events.length} event(s) restored`);
  } else if (last.action === 'editEvent') {
    const idx = calendarEvents.findIndex(e => String(e.id) === last.eventId);
    if (idx !== -1) calendarEvents[idx] = last.after;
    saveToLocalStorage(); renderCalendar(); renderStats(); renderUpcoming(); renderDaEvents(); renderLifecycleProgress();
    showToast('↪️ Edit redone');
  }
}

// ======================================================================
// SECTION: MODE + VIEW SWITCH
// ======================================================================

function switchCalendarMode(mode) {
  calendarMode = mode;
  const isPersonal = mode === 'personal';
  document.getElementById('modeMyFarm')?.classList.toggle('active', isPersonal);
  document.getElementById('modeCommunity')?.classList.toggle('active', !isPersonal);

  const titleEl = document.getElementById('calendarTitle');
  const subEl   = document.getElementById('calendarSubtitle');
  if (titleEl) {
    if (isPersonal) {
      updateCalendarTitle();
    } else {
      titleEl.innerHTML = '<i class="fas fa-users"></i> Community Calendar';
    }
  }
  if (subEl) {
    subEl.textContent = isPersonal ? `Your Personal Planting Tracker` : `Public Posts from Farmers & Admins`;
  }

  document.querySelector('main.content').classList.toggle('community-mode', !isPersonal);

  const badge = document.getElementById('miniCalBadge');
  const card  = document.getElementById('miniCalCard');
  if (badge) badge.innerHTML = isPersonal ? '<i class="fas fa-users"></i> Community' : '<i class="fas fa-seedling"></i> My Farm';
  if (card)  card.classList.toggle('community-mode', !isPersonal);

  const addBtn = document.getElementById('addEventBtn');
  if (addBtn) addBtn.style.visibility = isPersonal ? 'visible' : 'hidden';

  renderCalendar(); renderStats(); renderUpcoming(); renderDaEvents(); renderLifecycleProgress(); renderMiniCalendar();
  showToast(isPersonal ? '🌱 Switched to My Farm' : '👥 Switched to Community');
}

function toggleCalendarMode() {
  const panels = document.querySelectorAll('.cal-view-panel:not(.hidden)');
  panels.forEach(p => p.classList.add('swapping'));
  setTimeout(() => {
    switchCalendarMode(calendarMode === 'personal' ? 'community' : 'personal');
    panels.forEach(p => p.classList.remove('swapping'));
  }, 220);
}

function switchView(view) {
  currentView = view;
  document.getElementById('monthView').classList.toggle('hidden', view !== 'month');
  document.getElementById('todayView').classList.toggle('hidden', view !== 'today');
  document.getElementById('weekView').classList.toggle('hidden',  view !== 'week');
  document.getElementById('viewMonth').classList.toggle('active', view === 'month');
  document.getElementById('viewToday').classList.toggle('active', view === 'today');
  document.getElementById('viewWeek')?.classList.toggle('active', view === 'week');
  if (view === 'today') renderTodayView();
  if (view === 'week')  { weekOffset = 0; renderWeekView(); }
}

// ======================================================================
// SECTION: TODAY VIEW
// ======================================================================

function renderTodayView() {
  const el      = document.getElementById('todayViewContent');
  const today   = new Date(); today.setHours(0,0,0,0);
  const dateKey = getDateKey(today);
  const dow     = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
  const mons    = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  const events  = getActiveEvents().filter(e => e.dateKey === dateKey);
  const tips    = ['January: Good time for dry-season corn planting in Mindanao.','February: Prepare seedbeds for wet-season rice. Monitor for aphids.','March: Ideal for vegetable planting before the rains. Fertilize coconuts.','April: Start wet-season rice seedbeds. Watch for heat stress on crops.','May: Transplant rice seedlings. Plant corn before heavy rains set in.','June: Peak rainy season — monitor for fungal diseases and flooding.','July: Second fertilizer application for rice. Weed control critical.','August: Watch for brown planthopper in rice fields.','September: Harvest dry-season corn. Prepare for early rice harvest.','October: Wet-season rice harvest begins. Dry palay promptly.','November: Plant dry-season corn and vegetables. Fertilize banana.','December: Good for cassava and sweet potato planting. Market season peaks.'];

  const defaultHour = { task:6, planting:6, weeding:6, fertilizer:7, irrigation:7, pest:8, harvest:6, da:8, market:5, vaccination:8, note:9 };
  const scheduled = events.map(e => {
    const m = e.title.match(/@\s*(\d+):(\d+)/);
    return { ...e, displayHour: m ? parseInt(m[1]) : (defaultHour[e.type] || 8), hasExplicit: !!m };
  });

  const hours = Array.from({ length: 15 }, (_, i) => i + 5);
  const timelineHTML = hours.map(h => {
    const label = h < 12 ? `${h}:00 AM` : h === 12 ? '12:00 PM' : `${h-12}:00 PM`;
    const atH   = scheduled.filter(e => e.displayHour === h);
    return `<div class="timeline-row ${atH.length ? 'has-event' : ''}">
      <div class="timeline-time">${label}</div>
      <div class="timeline-content">
        ${atH.map(e => `<div class="timeline-event-pill type-${e.type}" title="${e.notes || ''}">${e.emoji} ${e.title.replace(/@\s*\d+:\d+/, '').trim()}${!e.hasExplicit ? '<span style="font-size:9px;opacity:.6;margin-left:4px">approx.</span>' : ''}</div>`).join('')}
      </div>
    </div>`;
  }).join('');

  el.innerHTML = `
    <div class="today-view-wrap">
      <div class="today-header">
        <div class="today-date-big">${today.getDate()}</div>
        <div>
          <div class="today-dow">${dow[today.getDay()]}</div>
          <div class="today-month">${mons[today.getMonth()]} ${today.getFullYear()}</div>
          <div class="today-moon">${getMoonPhase(today)} ${getMoonPhaseName(today)}</div>
        </div>
      </div>
      <div class="today-suggestion"><i class="fas fa-lightbulb"></i><span><strong>DA Tip for ${mons[today.getMonth()]}:</strong> ${tips[today.getMonth()]}</span></div>
      <div class="today-two-col">
        <div>
          <h4 class="today-section-title"><i class="fas fa-clock"></i> Timeline</h4>
          <div class="today-timeline">${timelineHTML}</div>
        </div>
        <div>
          <h4 class="today-section-title"><i class="fas fa-tasks"></i> Today's Tasks (${events.length})</h4>
          ${events.length === 0
            ? `<div class="today-empty"><div style="font-size:32px;margin-bottom:8px">🌤️</div><p>No tasks today.</p><button onclick="openAddEventModalForDay('${dateKey}')" class="btn primary" style="margin-top:8px;font-size:13px;"><i class="fas fa-plus"></i> Add a task</button></div>`
            : events.map(e => `
                <div class="today-task-row" onclick="openDayDetail('${dateKey}')">
                  <div class="today-task-icon">${e.emoji}</div>
                  <div>
                    <div class="today-task-title">${e.title}</div>
                    ${e.location ? `<div class="today-task-meta">📍 ${e.location}</div>` : ''}
                    ${e.notes ? `<div class="today-task-meta">📝 ${e.notes.slice(0,60)}${e.notes.length>60?'…':''}</div>` : ''}
                  </div>
                </div>`).join('')}
          <div style="margin-top:12px">
            <button onclick="openAddEventModalForDay('${dateKey}')" class="btn secondary" style="width:100%;font-size:13px;"><i class="fas fa-plus"></i> Add Task for Today</button>
          </div>
        </div>
      </div>
    </div>`;
}

// ======================================================================
// SECTION: WEEK VIEW
// ======================================================================

function renderWeekView() {
  const el  = document.getElementById('weekViewContent');
  if (!el) return;
  const today    = new Date(); today.setHours(0,0,0,0);
  const base     = new Date(today);
  base.setDate(today.getDate() - today.getDay() + (weekOffset * 7));
  const days     = Array.from({ length: 7 }, (_, i) => { const d = new Date(base); d.setDate(base.getDate()+i); return d; });
  const mons     = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  const dows     = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
  const todayKey = getDateKey(new Date());

  const headerHTML = days.map(d => {
    const isT = getDateKey(d) === todayKey;
    return `<div class="week-col-header${isT ? ' week-today' : ''}">
      <div class="week-dow">${dows[d.getDay()]}</div>
      <div class="week-date-num${isT ? ' week-date-today' : ''}">${d.getDate()}</div>
      <div class="week-month-lbl">${mons[d.getMonth()]}</div>
    </div>`;
  }).join('');

  const eventsHTML = days.map(d => {
    const dk  = getDateKey(d);
    const isT = dk === todayKey;
    const evs = getActiveEvents().filter(e => {
      if (e.dateKey !== dk) return false;
      if (calendarMode === 'community') return true;
      if (e.type === 'task' || e.type === 'harvest' || e.type === 'pest') return activeLayers.tasks;
      if (e.type === 'da')     return activeLayers.da;
      if (e.type === 'market') return activeLayers.market;
      return true;
    });
    return `<div class="week-col-events${isT ? ' week-today-col' : ''}">
      ${evs.map(e => `<div class="week-event-pill type-${e.type}" onclick="openDayDetail('${dk}')" title="${(e.notes||'').replace(/"/g,'&quot;')}">${e.emoji} <span>${e.title}</span></div>`).join('')}
      ${calendarMode === 'personal' ? `<button class="week-add-btn" onclick="openAddEventModalForDay('${dk}')" title="Add event">+</button>` : ''}
    </div>`;
  }).join('');

  const rangeLabel = days[0].getMonth() === days[6].getMonth()
    ? `${mons[days[0].getMonth()]} ${days[0].getDate()}–${days[6].getDate()}, ${days[0].getFullYear()}`
    : `${mons[days[0].getMonth()]} ${days[0].getDate()} – ${mons[days[6].getMonth()]} ${days[6].getDate()}, ${days[6].getFullYear()}`;

  el.innerHTML = `
    <div class="week-view-wrap">
      <div class="week-nav">
        <button onclick="prevWeek()" class="nav-arrow"><i class="fas fa-chevron-left"></i></button>
        <span class="week-range-label">${rangeLabel}</span>
        <button onclick="nextWeek()" class="nav-arrow"><i class="fas fa-chevron-right"></i></button>
        <button onclick="weekOffset=0;renderWeekView();" class="nav-today-btn">This Week</button>
      </div>
      <div class="week-grid">
        <div class="week-header-row">${headerHTML}</div>
        <div class="week-events-row">${eventsHTML}</div>
      </div>
    </div>`;
}

function prevWeek() { weekOffset--; renderWeekView(); }
function nextWeek() { weekOffset++; renderWeekView(); }

// ======================================================================
// SECTION: MINI CALENDAR
// ======================================================================

function renderMiniCalendar() {
  const grid  = document.getElementById('miniCalGrid');
  const label = document.getElementById('miniCalMonthLabel');
  if (!grid) return;
  const mons = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  if (label) label.textContent = `${mons[currentMonth]} ${currentYear}`;
  const firstDay    = new Date(currentYear, currentMonth, 1).getDay();
  const daysInMonth = new Date(currentYear, currentMonth+1, 0).getDate();
  const todayKey    = getDateKey(new Date());
  const events      = getActiveEvents();
  let html = '';
  for (let i = 0; i < firstDay; i++) html += '<div class="mini-cal-day"></div>';
  for (let d = 1; d <= daysInMonth; d++) {
    const dk       = `${currentYear}-${String(currentMonth+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
    const isToday  = dk === todayKey;
    const hasEvent = events.some(e => e.dateKey === dk);
    html += `<div class="mini-cal-day${isToday?' mini-today':''}${hasEvent?' mini-has-event':''}">${d}</div>`;
  }
  // Fill to 42 cells so height is always stable (6 rows × 7 cols)
  const filled = firstDay + daysInMonth;
  for (let i = filled; i < 42; i++) html += '<div class="mini-cal-day"></div>';
  grid.innerHTML = html;
}

// ======================================================================
// SECTION: LIFECYCLE PROGRESS
// ======================================================================

function renderLifecycleProgress() {
  const el = document.getElementById('lifecycleProgress');
  if (!el) return;
  const todayKey  = getDateKey(new Date());
  const lifecycles = {};
  calendarEvents.forEach(e => {
    if (!e.lifecycleId) return;
    if (!lifecycles[e.lifecycleId]) lifecycles[e.lifecycleId] = { crop: e.crop, events: [] };
    lifecycles[e.lifecycleId].events.push(e);
  });
  const active = Object.values(lifecycles).filter(lc => {
    const dates = lc.events.map(e => e.dateKey).sort();
    return dates[0] <= todayKey && dates[dates.length-1] >= todayKey;
  });
  if (!active.length) {
    el.innerHTML = '<p style="color:#888;font-size:12px;padding:4px 0">No active crop lifecycles. Plant a crop to start tracking!</p>';
    return;
  }
  const cropEmojis = { rice:'🌾', corn:'🌽', vegetables:'🥬', banana:'🍌', coconut:'🥥', cassava:'🍠', sweetPotato:'🍠' };
  el.innerHTML = active.map(lc => {
    const sorted   = [...lc.events].sort((a,b) => a.dateKey.localeCompare(b.dateKey));
    const start    = sorted[0].dateKey;
    const end      = sorted[sorted.length-1].dateKey;
    const total    = Math.max(1, Math.round((new Date(end+'T00:00:00') - new Date(start+'T00:00:00')) / 86400000));
    const elapsed  = Math.round((new Date(todayKey+'T00:00:00') - new Date(start+'T00:00:00')) / 86400000);
    const pct      = Math.min(100, Math.max(0, Math.round((elapsed / total) * 100)));
    const done     = sorted.filter(e => e.dateKey <= todayKey);
    const next     = sorted.find(e => e.dateKey > todayKey);
    const emoji    = cropEmojis[lc.crop] || '🌱';
    const daysLeft = getDaysUntil(end);
    return `<div class="lifecycle-progress-card">
      <div class="lc-header">
        <span class="lc-crop">${emoji} ${lc.crop ? lc.crop.charAt(0).toUpperCase() + lc.crop.slice(1) : 'Crop'}</span>
        <span class="lc-pct">${pct}%</span>
      </div>
      <div class="lc-bar-bg"><div class="lc-bar-fill" style="width:${pct}%"></div></div>
      <div class="lc-meta">Day ${elapsed} of ${total} • ${daysLeft > 0 ? daysLeft + 'd remaining' : '🏁 Final stage'}</div>
      ${done.length ? `<div class="lc-last">✅ ${done[done.length-1].title}</div>` : ''}
      ${next ? `<div class="lc-next">⏭️ ${next.title} in ${getDaysUntil(next.dateKey)}d</div>` : '<div class="lc-next">🎉 Harvest is here!</div>'}
    </div>`;
  }).join('');
}

// ======================================================================
// SECTION: RECURRING EVENTS GENERATOR
// ======================================================================

function generateRecurringInstances(baseEvent, recurrence) {
  const instances        = [];
  const baseDate         = new Date(baseEvent.dateKey+'T00:00:00');
  const maxInstances     = recurrence === 'monthly' ? 12 : recurrence === 'biweekly' ? 26 : 52;
  const recurrenceGroupId = `rec_${Date.now()}`;
  for (let i = 0; i < maxInstances; i++) {
    const d = new Date(baseDate);
    if      (recurrence === 'monthly')   d.setMonth(d.getMonth() + i);
    else if (recurrence === 'biweekly') d.setDate(d.getDate() + 14 * i);
    else                                d.setDate(d.getDate() + 7 * i);
    instances.push({ ...baseEvent, id: `${Date.now()}_${i}_${Math.floor(Math.random()*99999)}`, dateKey: getDateKey(d), recurrenceGroupId, recurrence, autoGenerated: i > 0 });
  }
  return instances;
}

// ======================================================================
// SECTION: UTILITY
// ======================================================================

function showToast(msg) {
  const t = document.getElementById('toast');
  t.textContent = msg; t.style.display = 'block';
  clearTimeout(t._timer);
  t._timer = setTimeout(() => { t.style.display = 'none'; }, 3200);
}

function setTheme(mode) {
  document.body.classList.toggle('dark-theme', mode === 'dark');
  showToast(mode === 'dark' ? '🌙 Dark mode on' : '☀️ Light mode on');
}

function exportCalendarPDF() {
  showToast('🖨️ Opening print dialog...');
  setTimeout(() => window.print(), 600);
}

function showFieldError(fieldId) {
  const el = document.getElementById(fieldId);
  if (!el) return;
  el.classList.add('field-error');
  el.focus();
  setTimeout(() => el.classList.remove('field-error'), 2500);
}

// ======================================================================
// SECTION: KEYBOARD SHORTCUTS
// ======================================================================

document.addEventListener('keydown', e => {
  if (e.ctrlKey && e.key === 'z') { e.preventDefault(); undoLastAction(); }
  if (e.ctrlKey && e.key === 'y') { e.preventDefault(); redoLastAction(); }
  if (e.key === 'Escape') {
    ['addEventModal','dayDetailModal','weatherDetailModal'].forEach(id => document.getElementById(id)?.classList.add('hidden'));
    // Close profile dropdown
    document.getElementById('profile-dropdown')?.classList.remove('open');
    document.getElementById('profile-overlay')?.classList.remove('open');
  }
  if (e.key === 'ArrowLeft'  && !e.target.matches('input,textarea,select')) prevMonth();
  if (e.key === 'ArrowRight' && !e.target.matches('input,textarea,select')) nextMonth();
});

// ======================================================================
// SECTION: LOCAL STORAGE
// ======================================================================

function saveToLocalStorage() {
  try { localStorage.setItem('roots_cal_events', JSON.stringify(calendarEvents)); }
  catch (e) { console.warn('Could not save to localStorage:', e); }
}

function loadFromLocalStorage() {
  try {
    const saved = localStorage.getItem('roots_cal_events');
    if (saved) {
      const parsed = JSON.parse(saved);
      if (Array.isArray(parsed) && parsed.length > 0) calendarEvents = parsed;
    }
  } catch (e) { console.warn('Could not load from localStorage:', e); }
}

// ======================================================================
// SECTION: CONFETTI
// ======================================================================

function triggerConfetti() {
  const canvas = document.createElement('canvas');
  canvas.style.cssText = 'position:fixed;top:0;left:0;width:100%;height:100%;pointer-events:none;z-index:99999';
  document.body.appendChild(canvas);
  canvas.width = innerWidth; canvas.height = innerHeight;
  const ctx    = canvas.getContext('2d');
  const colors = ['#4CAF50','#ffd700','#e74c3c','#3498db','#f39c12','#52b788','#ff6b9d','#a8e063'];
  const pieces = Array.from({ length: 90 }, () => ({
    x: Math.random() * innerWidth, y: -20 - Math.random() * 60,
    w: 7 + Math.random() * 9, h: 4 + Math.random() * 5,
    color: colors[Math.floor(Math.random() * colors.length)],
    vx: (Math.random() - 0.5) * 5, vy: 2.5 + Math.random() * 4,
    rot: Math.random() * 360, vr: (Math.random() - 0.5) * 9
  }));
  let frame;
  function draw() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    pieces.forEach(p => {
      p.x += p.vx; p.y += p.vy; p.rot += p.vr; p.vy += 0.05;
      ctx.save();
      ctx.translate(p.x, p.y); ctx.rotate(p.rot * Math.PI / 180);
      ctx.fillStyle = p.color; ctx.globalAlpha = Math.max(0, 1 - p.y / canvas.height * 1.4);
      ctx.fillRect(-p.w/2, -p.h/2, p.w, p.h);
      ctx.restore();
    });
    if (pieces.some(p => p.y < canvas.height + 30)) frame = requestAnimationFrame(draw);
    else { cancelAnimationFrame(frame); canvas.remove(); }
  }
  draw();
  setTimeout(() => { cancelAnimationFrame(frame); canvas.remove(); }, 4000);
}